name: static checks
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  gofmt:
    name: "Ensure the code is shellchecked"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "ShellCheck"
        run: make lint
